const fakeApi = {
  FB: {
    symbol: 'FB',
    companyName: 'Facebook Inc.',
    primaryExchange: 'Nasdaq Global Select',
    sector: 'Technology',
    calculationPrice: 'close',
    latestPrice: 166.32,
    latestSource: 'Previous close',
    latestTime: 'August 25, 2017',
    latestVolume: 3413166,
    delayedPrice: 166.23,
    delayedPriceTime: 1503694755437,
    previousClose: 166.32,
    change: 0,
    changePercent: 0,
    avgTotalVolume: 17954672,
    marketCap: 483025975851,
    peRatio: 37.12,
    week52High: 175.49,
    week52Low: 113.5535,
  },
  MSFT: {
    symbol: 'MSFT',
    companyName: 'Microsoft Corporation',
    primaryExchange: 'Nasdaq Global Select',
    sector: 'Technology',
    calculationPrice: 'close',
    latestPrice: 72.82,
    latestSource: 'Previous close',
    latestTime: 'August 25, 2017',
    latestVolume: 2739340,
    delayedPrice: 72.65,
    delayedPriceTime: 1503694621877,
    previousClose: 72.82,
    change: 0,
    changePercent: 0,
    avgTotalVolume: 22343780,
    marketCap: 560877406551,
    peRatio: 25.11,
    week52High: 74.42,
    week52Low: 55.61,
  },
  FAKESYMBOL: {
    symbol: 'FAKE_SYMBOL',
    companyName: null,
    primaryExchange: null,
    sector: null,
    calculationPrice: 'close',
    latestPrice: null,
    latestSource: 'N/A',
    latestTime: 'N/A',
    latestVolume: 0,
    delayedPrice: null,
    delayedPriceTime: null,
    previousClose: 'N/A',
    change: 'N/A',
    changePercent: 'N/A',
    avgTotalVolume: 0,
    marketCap: 'N/A',
    peRatio: 'N/A',
    week52High: 0,
    week52Low: 0,
  },
};

const fakeStore = {
  initialState: {
    loading: false,
    data: [],
    error: '',
  },
  successState: {
    loading: false,
    data: [fakeApi.FB, fakeApi.MSFT],
    error: '',
  },
  failState: {
    loading: false,
    data: [],
    error: 'Error retrieving information of symbol(s): FAKE_SYMBOL',
  },
};

export { fakeStore, fakeApi };
